/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package net.yazeed44.syncutil;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author yazeed44
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
      private boolean isWindows = true;
    File importFile;
    private boolean chooseFile = false;
    String numbers;
    
    private boolean debug = false;
    
    private String username,password;
    
    private String mode,context;
    public Main() {
        initComponents();
        initVars();
        initIsWindows();
        this.setTitle("WhatsApi Sync util (Java)");
    }

    private void initIsWindows(){
        int result =JOptionPane.showOptionDialog(this, "What is your operating System ?","" , JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE
                , null, new String[]{"GNU/Linux or mac","Windows"}, null);
        
        if(result == 0){
            JOptionPane.showMessageDialog(this, "you must install mono to use this program "+"\n" + "in Gnu/linux : open terminal and type " +"\n"
                    +"sudo apt-get install mono" +"\n" +"in mac : i don't know :D just search and you will find a way"
                    , "", JOptionPane.WARNING_MESSAGE);
            isWindows = false;
        }
        
        else {
            JOptionPane.showMessageDialog(this, "You are good to go !!", "", JOptionPane.INFORMATION_MESSAGE);
            isWindows = true;
        }
    }
  
    private void initVars(){
        this.txtRadioBtn.addActionListener(new Listener());
        txtRadioBtn.setActionCommand(txtRadioBtn.getText());
        
        numberRadioBtn.addActionListener(new Listener());
        numberRadioBtn.setActionCommand(numberRadioBtn.getText());
        
        ButtonGroup group = new ButtonGroup();
        group.add(txtRadioBtn);
        group.add(numberRadioBtn);
        
        
        debugCheck.setActionCommand(debugCheck.getText());
        debugCheck.addItemListener(new ItemListener(){
          
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (debug){
                    debug = false;
                    return;
                }
                     debug = true;
            }
            
        });
        
        
        
    }
    
    class Listener implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
           if (e.getActionCommand().equals(txtRadioBtn.getText())){
               final JFileChooser fc = new JFileChooser();
               fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
               
               fc.setAcceptAllFileFilterUsed(false);
               
               if(!chooseFile){
                   int returnVal = fc.showOpenDialog(Main.this);
                   
                   if (returnVal == JFileChooser.APPROVE_OPTION){
                       importFile = fc.getSelectedFile();
                       chooseFile = true;
                       System.out.println("We got file " + importFile.getPath());
                       numbers = null;
                   }
               }
               
               else  {
                   
               }
           }
           
           else if (e.getActionCommand().equals(numberRadioBtn.getText())){
              numbers =  JOptionPane.showInputDialog(Main.this, "Enter the numbers seperated by space :"
                      + "\n" + "Example : 96653493848 96654473728", "Enter the numbers", JOptionPane.QUESTION_MESSAGE);
              importFile = null;
           }
           
           
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtRadioBtn = new javax.swing.JRadioButton();
        numberRadioBtn = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        usernameTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        contextCombo = new javax.swing.JComboBox();
        modeCombo = new javax.swing.JComboBox();
        debugCheck = new javax.swing.JCheckBox();
        syncBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Whatsapp Sync Util");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Numbers input method : ");

        txtRadioBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRadioBtn.setText("through txt file");

        numberRadioBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        numberRadioBtn.setText("type the numbers");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtRadioBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numberRadioBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(txtRadioBtn)
                .addGap(18, 18, 18)
                .addComponent(numberRadioBtn)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel4.setText("User name (your phone number)");

        jLabel5.setText("your whatsapp password");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Options");

        jLabel7.setText("Context");

        jLabel8.setText("Mode");

        contextCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "registration", "background", "interactive" }));

        modeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "full", "delta" }));

        debugCheck.setText("debug");
        debugCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debugCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(debugCheck))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(contextCombo, 0, 118, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(32, 32, 32)
                .addComponent(debugCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contextCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(34, 34, 34))
        );

        syncBtn.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        syncBtn.setText("Sync");
        syncBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                syncBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(52, 52, 52)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(syncBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(39, 39, 39)
                .addComponent(syncBtn)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void debugCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debugCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debugCheckActionPerformed

    private void syncBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syncBtnActionPerformed
        // TODO add your handling code here:
        
        username = usernameTxt.getText();
        password = passwordTxt.getText();
        mode = (String)modeCombo.getSelectedItem();
        context = (String)contextCombo.getSelectedItem();
        boolean isUserInputTxt = true;
        
        if(!isVarsInitalized())
            return;
        
        
        //let's get numbers !!
       
        else if (numbers != null){
            isUserInputTxt = false;
            
        }
        else if (importFile != null){
            isUserInputTxt = true;
            BufferedReader buffer = null;
            numbers = "";
            try {
                 buffer = new BufferedReader(new FileReader(importFile));
                 String line="";
            while((line = buffer.readLine()) != null){
                numbers+=line +" ";
            }
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex, "Exception !!", JOptionPane.ERROR_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex, "Exception !!", JOptionPane.ERROR_MESSAGE);
            }
            
        }
                        System.out.println("numbers = " + numbers);
        
        String command ="";
        
        if (!isWindows){
            command += "mono ";
        }
        
        command += "wasyncutil.exe" +" username=";
        command+= username +" ";
        command+="password="+password;
        command+=" mode="+mode;
        command+=" debug="+debug;
        command+=" context="+context;
        command+=" "+numbers;
        
        System.out.println("command : " + "\n" + command);
        String line="";
        String result = "";
        Process proc;
          try {
              proc = Runtime.getRuntime().exec(command);
               BufferedReader reader = 
            new BufferedReader(new InputStreamReader(proc.getInputStream()));

        
        while((line = reader.readLine()) != null) {
            System.out.print(line + "\n");
            result += line +"\n";
        }

        proc.waitFor();  
          } catch (IOException | InterruptedException ex) {
              Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
          }

          System.out.println("result : " + "\n" + result);
       if(result.contains("Exception")){
           JOptionPane.showMessageDialog(this, "There's a exception : " +"\n"+result, "", JOptionPane.ERROR_MESSAGE);
           return;
       }
       else if(result.contains("ERROR")){
           JOptionPane.showMessageDialog(this, "There's an error !! " + "\n" + result, "", JOptionPane.ERROR_MESSAGE);
           return;
       }
       
       else if (result.contains("failed")){
           JOptionPane.showMessageDialog(this,"" + result,"",JOptionPane.ERROR_MESSAGE);
           return;
       }
       
       else if (result.length() > 1){
          
           int copy = JOptionPane.showOptionDialog(this, "the phone numbers who does have a whatsapp :  " + "\n" + result
                   , "",JOptionPane.YES_OPTION, JOptionPane.INFORMATION_MESSAGE
                   , null, new String[]{"Copy the numbers"}, null);
           
           if (copy == 0){
               setSysClipboardText(result);
               
           }
           return;
       }
       
     /*  else if (result.length() == 0){
           JOptionPane.showMessageDialog(this, "Nobody got whatsapp!!"+ "\n"+ "Ohhhh!! I know that feeling bro !!", "", JOptionPane.INFORMATION_MESSAGE);
           return;
       }*/
        
    }//GEN-LAST:event_syncBtnActionPerformed

    private boolean isVarsInitalized(){
        
        if (username == null||username.length() == 0){
            JOptionPane.showMessageDialog(this, "you didn't type a username", "ERROR !!", JOptionPane.ERROR_MESSAGE);
            return false;
            
        }
        
        if (password == null ||password.length() == 0){
            JOptionPane.showMessageDialog(this, "you didn't type a password", "ERROR !!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
         if(numbers == null&&importFile ==null){
            JOptionPane.showMessageDialog(this, "You didn't put numbers !!", "", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
        
    }
    
   /**
     * put string into Clipboard
     */
    public static void setSysClipboardText(String writeMe) {
        Clipboard clip = Toolkit.getDefaultToolkit().getSystemClipboard();
        Transferable tText = new StringSelection(writeMe);
        clip.setContents(tText, null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox contextCombo;
    private javax.swing.JCheckBox debugCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox modeCombo;
    private javax.swing.JRadioButton numberRadioBtn;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JButton syncBtn;
    private javax.swing.JRadioButton txtRadioBtn;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
